// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	_go "github.com/Eternity8c/proto-shop/auth-proto/gen/go/api/proto"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserAuth is an autogenerated mock type for the UserAuth type
type UserAuth struct {
	mock.Mock
}

// IsAdmin provides a mock function with given fields: ctx, userID
func (_m *UserAuth) IsAdmin(ctx context.Context, userID int64) (bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsAdmin")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *UserAuth) Login(ctx context.Context, email string, password string) (*_go.LoginResponse, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *_go.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*_go.LoginResponse, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *_go.LoginResponse); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*_go.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, email, password, fullName
func (_m *UserAuth) Register(ctx context.Context, email string, password string, fullName string) (*_go.RegisterResponse, error) {
	ret := _m.Called(ctx, email, password, fullName)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *_go.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*_go.RegisterResponse, error)); ok {
		return rf(ctx, email, password, fullName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *_go.RegisterResponse); ok {
		r0 = rf(ctx, email, password, fullName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*_go.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, password, fullName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserAuth creates a new instance of UserAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserAuth {
	mock := &UserAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
